---
title: "Task 3"
author: "Nicole Hawe"
date: "October 3, 2017"
output: github_document
---

```{r}
library(gapminder)
library(tidyverse)
library(knitr)
library(kableExtra)
```



#### Compute a trimmed mean of life expectancy for different years. Or a weighted mean, weighting by population. Just try something other than the plain vanilla mean.

For this question I decided to tackle *trimmed mean*:

```{r}
n5 <- gapminder %>% 
  group_by(year) %>% 
  summarise(trim_mean_lifeExp = mean(lifeExp, trim=0.25)) %>% 
  arrange(year) %>% 
  select(year, trim_mean_lifeExp)

# I grouped by year, and then used summarize not mutate in order to collaspe the years into one row not add columns with the trimmed mean but having multiple years

kable(n5)



  
  
  
```

Then I went on to visualize this trimmed mean life expectancy using a line graph:

```{r}
ggplot(n5, aes(x=year, y=trim_mean_lifeExp)) +
  geom_point(colour="purple", size=3) +
  geom_line()+
  labs(x="Year", y="Trimmed Mean LifeExp")+
  ggtitle("Trimmed Mean Life Expectancy") +
  theme(plot.title = element_text(hjust=0.5))
```


